
Organizations:
    - &OrdererIntegra
   
        Name: OrdererIntegra

        # ID to load the MSP definition as
        ID: ordererMSP

        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: ../organizations/ordererOrganizations/integra.com/msp

       
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('ordererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('ordererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('ordererMSP.admin')"
        OrdererEndpoints:
        - orderer.example.com:7050        


    - &Integra
       
        Name: integraMSP
        

        # ID to load the MSP definition as
        ID: integraMSP

        MSPDir: ../organizations/peerOrganizations/integra.integra.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('integraMSP.admin', 'integraMSP.peer', 'integraMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('integraMSP.admin', 'integraMSP.client', 'integraMSP.orderer')"
            Admins:
                Type: Signature
                Rule: "OR('integraMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('integraMSP.peer')"

        OrdererEndpoints:
            - orderer0.integra.integra.com:7050

        AnchorPeers:
            - Host: peer0.integra.integra.com
              Port: 7051        

#     - &Bcp
    
#         Name: bcpMSP

#         # ID to load the MSP definition as
#         ID: bcpMSP

#         MSPDir: ../organizations/peerOrganizations/bcp.integra.com/msp

#         Policies:
#             Readers:
#                 Type: Signature
#                 Rule: "OR('bcpMSP.admin', 'bcpMSP.peer', 'bcpMSP.client')"
#             Writers:
#                 Type: Signature
#                 Rule: "OR('bcpMSP.admin', 'bcpMSP.client','bcpMSP.orderer')"
#             Admins:
#                 Type: Signature
#                 Rule: "OR('bcpMSP.admin')"
#             Endorsement:
#                 Type: Signature
#                 Rule: "OR('bcpMSP.peer')"

#         OrdererEndpoints:
#             - orderer0.bcp.integra.com:8050

#         AnchorPeers:       
#             - Host: peer0.bcp.integra.com
#               Port: 9051
              
#     - &Esp
        
#         Name: espMSP

#         # ID to load the MSP definition as
#         ID: espMSP

#         MSPDir: ../organizations/peerOrganizations/esp.integra.com/msp

       
#         Policies:
#             Readers:
#                 Type: Signature
#                 Rule: "OR('espMSP.admin', 'espMSP.peer', 'espMSP.client')"
#             Writers:
#                 Type: Signature
#                 Rule: "OR('espMSP.admin', 'espMSP.client','espMSP.orderer')"
#             Admins:
#                 Type: Signature
#                 Rule: "OR('espMSP.admin')"
#             Endorsement:
#                 Type: Signature
#                 Rule: "OR('espMSP.peer')"

#         OrdererEndpoints:
#             - orderer0.esp.integra.com:9050

#         AnchorPeers:
#             - Host: peer0.esp.integra.com
#               Port: 11051  

#     - &Broker
#         # DefaultOrg defines the organization which is used in the sampleconfig
#         # of the fabric.git development environment
#         Name: brokerMSP

#         # ID to load the MSP definition as
#         ID: brokerMSP

#         MSPDir: ../organizations/peerOrganizations/broker.integra.com/msp

#         # Policies defines the set of policies at this level of the config tree
#         # For organization policies, their canonical path is usually
#         #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
#         Policies:
#             Readers:
#                 Type: Signature
#                 Rule: "OR('brokerMSP.admin', 'brokerMSP.peer', 'brokerMSP.client')"
#             Writers:
#                 Type: Signature
#                 Rule: "OR('brokerMSP.admin', 'brokerMSP.client','brokerMSP.orderer')"
#             Admins:
#                 Type: Signature
#                 Rule: "OR('brokerMSP.admin')"
#             Endorsement:
#                 Type: Signature
#                 Rule: "OR('brokerMSP.peer')"

#         OrdererEndpoints:
#             - orderer0.broker.integra.com:10050

#         AnchorPeers:
#             # AnchorPeers defines the location of peers which can be used
#             # for cross org gossip communication.  Note, this value is only
#             # encoded in the genesis block in the Application section context
#             - Host: peer0.broker.integra.com
#               Port: 13051                    

# ################################################################################
# #
# #   SECTION: Capabilities

# ################################################################################
Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true

    Orderer: &OrdererCapabilities
        V2_0: true

    Application: &ApplicationCapabilities
        V2_0: true

# ################################################################################
# #
# #   SECTION: Application
# #
# ################################################################################
Application: &ApplicationDefaults

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:

    # Policies defines the set of policies at this level of the config tree
    # For Application policies, their canonical path is
    #   /Channel/Application/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"

    Capabilities:
        <<: *ApplicationCapabilities
# ################################################################################
# #
# #   SECTION: Orderer
# #
# ################################################################################
Orderer: &OrdererDefaults

    # Orderer Type: The orderer implementation to start
    OrdererType: etcdraft
    
    Addresses:
        - orderer.integra.com:7050
        - orderer2.integra.com:8050
        - orderer3.integra.com:9050
        - orderer4.integra.com:10050
        - orderer5.integra.com:11050

    EtcdRaft:
        Consenters:
        - Host: orderer.integra.com
          Port: 7050
          ClientTLSCert: ../organizations/ordererOrganizations/integra.com/orderers/orderer.integra.com/tls/server.crt
          ServerTLSCert: ../organizations/ordererOrganizations/integra.com/orderers/orderer.integra.com/tls/server.crt
        - Host: orderer2.integra.com
          Port: 8050
          ClientTLSCert: ../organizations/ordererOrganizations/integra.com/orderers/orderer2.integra.com/tls/server.crt
          ServerTLSCert: ../organizations/ordererOrganizations/integra.com/orderers/orderer2.integra.com/tls/server.crt
        - Host: orderer3.integra.com
          Port: 9050
          ClientTLSCert: ../organizations/ordererOrganizations/integra.com/orderers/orderer3.integra.com/tls/server.crt
          ServerTLSCert: ../organizations/ordererOrganizations/integra.com/orderers/orderer3.integra.com/tls/server.crt
        - Host: orderer4.integra.com
          Port: 10050
          ClientTLSCert: ../organizations/ordererOrganizations/integra.com/orderers/orderer4.integra.com/tls/server.crt
          ServerTLSCert: ../organizations/ordererOrganizations/integra.com/orderers/orderer4.integra.com/tls/server.crt
        - Host: orderer5.integra.com
          Port: 11050
          ClientTLSCert: ../organizations/ordererOrganizations/integra.com/orderers/orderer5.integra.com/tls/server.crt
          ServerTLSCert: ../organizations/ordererOrganizations/integra.com/orderers/orderer5.integra.com/tls/server.crt  



    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 2s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 99 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB

    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:

    # Policies defines the set of policies at this level of the config tree
    # For Orderer policies, their canonical path is
    #   /Channel/Orderer/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        # BlockValidation specifies what signatures must be included in the block
        # from the orderer for the peer to validate it.
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"


#     # Orderer Type: The orderer implementation to start
#     OrdererType: etcdraft
    
#     Addresses:
#         - orderer0.integra.integra.com:7050
#         - orderer0.bcp.integra.com:8050
#         - orderer0.esp.integra.com:9050
#         - orderer0.broker.integra.com:10050
        

#     EtcdRaft:
#         Consenters:
#         - Host: orderer0.integra.integra.com
#           Port: 7050
#           ClientTLSCert: ../organizations/peerOrganizations/integra.integra.com/peers/orderer0.integra.integra.com/tls/server.crt
#           ServerTLSCert: ../organizations/peerOrganizations/integra.integra.com/peers/orderer0.integra.integra.com/tls/server.crt
#         - Host: orderer0.bcp.integra.com
#           Port: 8050
#           ClientTLSCert: ../organizations/peerOrganizations/bcp.integra.com/peers/orderer0.bcp.integra.com/tls/server.crt
#           ServerTLSCert: ../organizations/peerOrganizations/bcp.integra.com/peers/orderer0.bcp.integra.com/tls/server.crt
#         - Host: orderer0.esp.integra.com
#           Port: 9050
#           ClientTLSCert: ../organizations/peerOrganizations/esp.integra.com/peers/orderer0.esp.integra.com/tls/server.crt
#           ServerTLSCert: ../organizations/peerOrganizations/esp.integra.com/peers/orderer0.esp.integra.com/tls/server.crt
#         - Host: orderer0.broker.integra.com
#           Port: 10050
#           ClientTLSCert: ../organizations/peerOrganizations/broker.integra.com/peers/orderer0.broker.integra.com/tls/server.crt
#           ServerTLSCert: ../organizations/peerOrganizations/broker.integra.com/peers/orderer0.broker.integra.com/tls/server.crt
        
#         # - Host: orderer5.integra.com
#         #   Port: 11050
#         #   ClientTLSCert: ../organizations/peerOrganizations/integra.com/peers/orderer5.integra.com/tls/server.crt
#         #   ServerTLSCert: ../organizations/peerOrganizations/integra.com/peers/orderer5.integra.com/tls/server.crt  



#     # Batch Timeout: The amount of time to wait before creating a batch
#     BatchTimeout: 2s

#     # Batch Size: Controls the number of messages batched into a block
#     BatchSize:

#         # Max Message Count: The maximum number of messages to permit in a batch
#         MaxMessageCount: 10

#         # Absolute Max Bytes: The absolute maximum number of bytes allowed for
#         # the serialized messages in a batch.
#         AbsoluteMaxBytes: 99 MB

#         # Preferred Max Bytes: The preferred maximum number of bytes allowed for
#         # the serialized messages in a batch. A message larger than the preferred
#         # max bytes will result in a batch larger than preferred max bytes.
#         PreferredMaxBytes: 512 KB

#     # Organizations is the list of orgs which are defined as participants on
#     # the orderer side of the network
# #     Organizations:

# #     # Policies defines the set of policies at this level of the config tree
# #     # For Orderer policies, their canonical path is
# #     #   /Channel/Orderer/<PolicyName>
# #     Policies:
# #         Readers:
# #             Type: ImplicitMeta
# #             Rule: "ANY Readers"
# #         Writers:
# #             Type: ImplicitMeta
# #             Rule: "ANY Writers"
# #         Admins:
# #             Type: ImplicitMeta
# #             Rule: "MAJORITY Admins"
# #         # BlockValidation specifies what signatures must be included in the block
# #         # from the orderer for the peer to validate it.
# #         BlockValidation:
# #             Type: ImplicitMeta
# #             Rule: "ANY Writers"
# #     Capabilities:
# #         <<: *OrdererCapabilities        

# ################################################################################
# #
# #   CHANNEL
# #
# ################################################################################
Channel: &ChannelDefaults
    Policies:
        # Who may invoke the 'Deliver' API
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        # Who may invoke the 'Broadcast' API
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        # By default, who may modify elements at this config level
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ChannelCapabilities

# ################################################################################
# #
# #   Profile
# #
# ################################################################################
Profiles:

    OrgsOrdererGenesis:
        <<: *ChannelDefaults
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererIntegra
            Capabilities:
                <<: *OrdererCapabilities
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Integra
            Capabilities: *ApplicationCapabilities
        # TwoOrgsApplicationGenesis:
        # <<: *ChannelDefaults
        # Orderer:
        #     <<: *OrdererDefaults
        #     Organizations:
        #         - *OrdererOrg
        #     Capabilities: *OrdererCapabilities
        # Application:
        #     <<: *ApplicationDefaults
        #     Organizations:
        #         - *Org1
        #         - *Org2
        #     Capabilities: *ApplicationCapabilities
                
    OrgsChannel:
        Consortium: IntegraConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Integra
                # - *Bcp
                # - *Esp
                # - *Broker
            Capabilities:
                <<: *ApplicationCapabilities

    MultiNodeEtcdRaft:
        <<: *ChannelDefaults
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            OrdererType: etcdraft
            EtcdRaft:
                Consenters:
                - Host: orderer.integra.com
                  Port: 7050
                  ClientTLSCert: ../organizations/ordererOrganizations/integra.com/orderers/orderer.integra.com/tls/server.crt
                  ServerTLSCert: ../organizations/ordererOrganizations/integra.com/orderers/orderer.integra.com/tls/server.crt
                - Host: orderer2.integra.com
                  Port: 7050
                  ClientTLSCert: ../organizations/ordererOrganizations/integra.com/orderers/orderer2.integra.com/tls/server.crt
                  ServerTLSCert: ../organizations/ordererOrganizations/integra.com/orderers/orderer2.integra.com/tls/server.crt
                - Host: orderer3.integra.com
                  Port: 7050
                  ClientTLSCert: ../organizations/ordererOrganizations/integra.com/orderers/orderer3.integra.com/tls/server.crt
                  ServerTLSCert: ../organizations/ordererOrganizations/integra.com/orderers/orderer3.integra.com/tls/server.crt
                - Host: orderer4.integra.com
                  Port: 7050
                  ClientTLSCert: ../organizations/ordererOrganizations/integra.com/orderers/orderer4.integra.com/tls/server.crt
                  ServerTLSCert: ../organizations/ordererOrganizations/integra.com/orderers/orderer4.integra.com/tls/server.crt
                - Host: orderer5.integra.com
                  Port: 7050
                  ClientTLSCert: ../organizations/ordererOrganizations/integra.com/orderers/orderer5.integra.com/tls/server.crt
                  ServerTLSCert: ../organizations/ordererOrganizations/integra.com/orderers/orderer5.integra.com/tls/server.crt

            Addresses:
                - orderer.integra.com:7050
                - orderer2.integra.com:8050
                - orderer3.integra.com:9050
                - orderer4.integra.com:10050
                - orderer5.integra.com:11050
                

            # Organizations:
            # - *OrdererIntegra
            Capabilities:
                <<: *OrdererCapabilities
        Application:
            <<: *ApplicationDefaults
            # Organizations:
            # - <<: *OrdererIntegra
        Consortiums:
            IntegraConsortium:
                Organizations:
                - *Integra
                # - *Bcp
                # - *Esp
                # - *Broker